import.package("ggplot2")
import.package("dplyr")
import.package("readr")
library(dplyr)
library(readr)
library(ggplot2)
salary_data <- read.csv("~/Downloads/salary_data.csv")
print(salary_data)
summary(salary_data)
anyNA(salary_data)
na.omit(salary_data)
head(airquality)
summary(airquality)
anyNA(airquality)
sum(is.na(airquality))
na_rows <- airquality[apply(airquality, 1, function(row) any(is.na(row))), ]
mean(airquality$Solar.R, na.rm = TRUE)
hist(airquality$Solar.R)
